#!/bin/bash
# scripts/deploy-on-server.sh
#
# Generic deploy script for both dev and prod environments. Runs on the VPS,
# invoked via SSH from a GitHub Actions workflow.
#
# Two modes:
#   - Branch mode (default): git pull --ff-only origin "$BRANCH"
#     Used by dev (auto-deploy on merge to main).
#   - Tag mode: git fetch --tags && git checkout "$BRANCH"
#     Used by prod (triggered by pushing a prod-* tag).
#     Mode is selected automatically: BRANCH starting with "prod-" = tag mode.
#
# Env variables (all optional):
#   REPO_DIR — where to deploy (default: /opt/pb-extension-dev)
#   BRANCH   — branch or tag to deploy (default: main)
#   ENV      — "dev" or "prod" (default: auto-detected from REPO_DIR)
#
# Handles known quirks:
#   - version.php is always regenerated at the end of this script. Before
#     pull/checkout we revert any local changes to it, otherwise git may
#     conflict with the previous deploy's stamp.
#   - config.php is locked with `chattr +i`, so `git pull` cannot touch it
#     (this is intentional — server-specific config is not in version control).

set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/pb-extension-dev}"
BRANCH="${BRANCH:-main}"

# Auto-detect ENV if not explicitly set.
# Convention: a REPO_DIR path containing "-dev" implies dev environment.
if [[ -z "${ENV:-}" ]]; then
  if [[ "$REPO_DIR" == *"-dev"* ]]; then
    ENV="dev"
  else
    ENV="prod"
  fi
fi

cd "$REPO_DIR"

echo "[deploy] $(date -u +%FT%TZ) starting deploy of '$BRANCH' to $REPO_DIR (env=$ENV)"
echo "[deploy] HEAD before: $(git rev-parse --short HEAD)"

# Revert version.php — it gets regenerated at the end of this script.
# Otherwise the previous deploy's stamp would conflict with git pull/checkout.
git checkout -- server/public/version.php 2>/dev/null || true

# Mode selection: tag if BRANCH starts with "prod-", else branch pull
if [[ "$BRANCH" == prod-* ]]; then
  echo "[deploy] tag mode — fetching tags and checking out '$BRANCH'"
  git fetch --tags
  git checkout "$BRANCH"
else
  echo "[deploy] branch mode — git pull --ff-only origin '$BRANCH'"
  git pull --ff-only origin "$BRANCH"
fi

DEPLOYED_COMMIT=$(git rev-parse --short HEAD)
echo "[deploy] HEAD after:  $DEPLOYED_COMMIT"

# Determine the deployed version string for the stamp.
# "version" tracks the EXTENSION version (from manifest.json or the tag), which
# can be the same across many server-only deploys. "commit" uniquely identifies
# the actual deployed code, so consecutive server-only deploys are always
# distinguishable in version.php and health.php.
if [[ "$BRANCH" == prod-* ]]; then
  # Strip "prod-v" or "prod-" prefix from the tag
  # e.g., "prod-v0.6.3" → "0.6.3"; "prod-hotfix" → "hotfix"
  DEPLOYED_VERSION="${BRANCH#prod-v}"
  DEPLOYED_VERSION="${DEPLOYED_VERSION#prod-}"
else
  # Branch mode: read version from chrome-extension/manifest.json
  DEPLOYED_VERSION=$(grep -oP '"version"\s*:\s*"\K[^"]+' "$REPO_DIR/chrome-extension/manifest.json" 2>/dev/null || echo "unknown")
fi

# Stamp version.php with the deployed version, commit, env, and build timestamp.
# This file is tracked in git but always overwritten here; the `git checkout`
# above ensures the previous deploy's stamp doesn't conflict with pull/checkout.
cat > "$REPO_DIR/server/public/version.php" <<PHP_EOF
<?php
// version.php — auto-generated by scripts/deploy-on-server.sh on each deploy.
// Do NOT commit local changes here; the deploy script reverts and regenerates.

return [
  'version'  => '$DEPLOYED_VERSION',
  'commit'   => '$DEPLOYED_COMMIT',
  'env'      => '$ENV',
  'built_at' => '$(date -u +%FT%TZ)',
];
PHP_EOF

echo "[deploy] stamped version.php: version=$DEPLOYED_VERSION commit=$DEPLOYED_COMMIT env=$ENV"

# Install this env's cron file from the repo (scripts/cron/pb-extension.cron.tmpl).
# Each env installs its OWN file from its OWN checkout, so prod's cron only
# changes when a prod tag deploys. A failure here warns but does NOT fail the
# deploy: monitoring must never block shipping a fix. The dashboard's
# "collector stale" banner shows if the cron stops running.
install_cron() {
  local tmpl="$REPO_DIR/scripts/cron/pb-extension.cron.tmpl"
  if [[ ! -f "$tmpl" ]]; then
    echo "[deploy] cron: no template at $tmpl — skipping"
    return 0
  fi
  # This writes a root-owned file into /etc/cron.d, so only accept the two
  # known checkout paths. The values also go into a sed replacement.
  if [[ ! "$REPO_DIR" =~ ^/opt/pb-extension(-dev)?$ ]]; then
    echo "[deploy] cron: WARNING unexpected REPO_DIR '$REPO_DIR' — not installing cron"
    return 0
  fi
  local name="pb-extension"
  [[ "$ENV" == "dev" ]] && name="pb-extension-dev"
  local dest="/etc/cron.d/$name"
  # Temp name starts with "." so cron ignores it until the atomic rename.
  local tmp
  tmp=$(mktemp /etc/cron.d/.pb-cron.XXXXXX) || { echo "[deploy] cron: WARNING mktemp failed"; return 0; }
  # Strip CRLF too: a Windows line ending makes cron silently ignore the line.
  sed -e "s#{{REPO_DIR}}#$REPO_DIR#g" -e 's/[[:cntrl:]]*$//' "$tmpl" > "$tmp"
  if grep -q '{{' "$tmp"; then
    echo "[deploy] cron: WARNING unreplaced placeholder in template — not installing"
    rm -f "$tmp"; return 0
  fi
  chown root:root "$tmp" && chmod 0644 "$tmp" && mv -f "$tmp" "$dest" \
    && echo "[deploy] cron: installed $dest" \
    || { echo "[deploy] cron: WARNING install failed"; rm -f "$tmp"; }
}
install_cron || echo "[deploy] cron: WARNING install_cron errored"

echo "[deploy] done"
