#!/bin/bash
# scripts/deploy-on-server.sh
#
# Generic deploy script for both dev and prod environments. Runs on the VPS,
# invoked via SSH from a GitHub Actions workflow.
#
# Two modes:
#   - Branch mode (default): git pull --ff-only origin "$BRANCH"
#     Used by dev (auto-deploy on merge to main).
#   - Tag mode: git fetch --tags && git checkout "$BRANCH"
#     Used by prod (triggered by pushing a prod-* tag).
#     Mode is selected automatically: BRANCH starting with "prod-" = tag mode.
#
# Env variables (all optional):
#   REPO_DIR — where to deploy (default: /opt/pb-extension-dev)
#   BRANCH   — branch or tag to deploy (default: main)
#   ENV      — "dev" or "prod" (default: auto-detected from REPO_DIR)
#
# Handles known quirks:
#   - version.php is always regenerated at the end of this script. Before
#     pull/checkout we revert any local changes to it, otherwise git may
#     conflict with the previous deploy's stamp.
#   - config.php is locked with `chattr +i`, so `git pull` cannot touch it
#     (this is intentional — server-specific config is not in version control).

set -euo pipefail

REPO_DIR="${REPO_DIR:-/opt/pb-extension-dev}"
BRANCH="${BRANCH:-main}"

# Auto-detect ENV if not explicitly set.
# Convention: a REPO_DIR path containing "-dev" implies dev environment.
if [[ -z "${ENV:-}" ]]; then
  if [[ "$REPO_DIR" == *"-dev"* ]]; then
    ENV="dev"
  else
    ENV="prod"
  fi
fi

cd "$REPO_DIR"

echo "[deploy] $(date -u +%FT%TZ) starting deploy of '$BRANCH' to $REPO_DIR (env=$ENV)"
echo "[deploy] HEAD before: $(git rev-parse --short HEAD)"

# Revert version.php — it gets regenerated at the end of this script.
# Otherwise the previous deploy's stamp would conflict with git pull/checkout.
git checkout -- server/public/version.php 2>/dev/null || true

# Mode selection: tag if BRANCH starts with "prod-", else branch pull
if [[ "$BRANCH" == prod-* ]]; then
  echo "[deploy] tag mode — fetching tags and checking out '$BRANCH'"
  git fetch --tags
  git checkout "$BRANCH"
else
  echo "[deploy] branch mode — git pull --ff-only origin '$BRANCH'"
  git pull --ff-only origin "$BRANCH"
fi

echo "[deploy] HEAD after:  $(git rev-parse --short HEAD)"

# Determine the deployed version string for the stamp.
if [[ "$BRANCH" == prod-* ]]; then
  # Strip "prod-v" or "prod-" prefix from the tag
  # e.g., "prod-v0.6.3" → "0.6.3"; "prod-hotfix" → "hotfix"
  DEPLOYED_VERSION="${BRANCH#prod-v}"
  DEPLOYED_VERSION="${DEPLOYED_VERSION#prod-}"
else
  # Branch mode: read version from chrome-extension/manifest.json
  DEPLOYED_VERSION=$(grep -oP '"version"\s*:\s*"\K[^"]+' "$REPO_DIR/chrome-extension/manifest.json" 2>/dev/null || echo "unknown")
fi

# Stamp version.php with the deployed version, env, and build timestamp.
# This file is tracked in git but always overwritten here; the `git checkout`
# above ensures the previous deploy's stamp doesn't conflict with pull/checkout.
cat > "$REPO_DIR/server/public/version.php" <<PHP_EOF
<?php
// version.php — auto-generated by scripts/deploy-on-server.sh on each deploy.
// Do NOT commit local changes here; the deploy script reverts and regenerates.

return [
  'version'  => '$DEPLOYED_VERSION',
  'env'      => '$ENV',
  'built_at' => '$(date -u +%FT%TZ)',
];
PHP_EOF

echo "[deploy] stamped version.php: version=$DEPLOYED_VERSION env=$ENV"
echo "[deploy] done"
