#!/usr/bin/env bash
#
# Generate PROJECT_MAP.md — a dependency map of the entire codebase.
#
# Usage:
#   ./scripts/generate-project-map.sh
#
# This script scans all PHP and JS source files and produces a machine-readable
# dependency map at the project root. It traces function definitions and callers,
# Chrome extension message flows, server endpoint usage, and shared helper usage.
#
# Run before every PR to keep the map current. Integrated via Claude Code hook.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$PROJECT_ROOT/PROJECT_MAP.md"

SERVER_DIR="$PROJECT_ROOT/server/public"
EXT_DIR="$PROJECT_ROOT/chrome-extension"

# Temp files
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# ── Helpers ───────────────────────────────────────────────────────────────

# Convert absolute path to relative from project root
relpath() {
  local abs="$1"
  abs="${abs//\\//}"
  local root="${PROJECT_ROOT//\\//}"
  echo "${abs#"$root"/}"
}

# grep -oE wrapper that silences errors
ogrep() {
  grep -oE "$@" 2>/dev/null || true
}

# ── Header ────────────────────────────────────────────────────────────────

TIMESTAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
COMMIT=$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "$OUTPUT" << 'HEADER'
# PROJECT_MAP.md — Dependency Map

<!-- AUTO-GENERATED by scripts/generate-project-map.sh — do not edit manually -->
HEADER

echo "<!-- Last generated: $TIMESTAMP | Commit: $COMMIT -->" >> "$OUTPUT"

cat >> "$OUTPUT" << 'INTRO'

This file maps every function, message type, endpoint, and dependency in the
project so that any change can be traced to everything it affects. Consult this
before modifying shared code.

---

INTRO

# ── Phase 1: File Inventory ──────────────────────────────────────────────

echo "## File Inventory" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Server PHP Files" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
find "$SERVER_DIR" -name '*.php' -not -path '*/vendor/*' | sort | while read -r f; do
  lines=$(wc -l < "$f")
  echo "$(relpath "$f")  ($lines lines)"
done >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Extension JS Files" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
find "$EXT_DIR" -name '*.js' | sort | while read -r f; do
  lines=$(wc -l < "$f")
  echo "$(relpath "$f")  ($lines lines)"
done >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ── Phase 2: Chrome Message Flow ─────────────────────────────────────────

echo "## Chrome Message Flow" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Maps every message type: where it's sent from, where it's handled, and what server endpoint it hits." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Message Type | Sent From | Handled In | Server Endpoint |" >> "$OUTPUT"
echo "|---|---|---|---|" >> "$OUTPUT"

BG="$EXT_DIR/background.js"
POP="$EXT_DIR/popup.js"
CS="$EXT_DIR/content.js"

# 1. Get all handled types from background.js (msg.type === "TYPE")
grep -oE 'msg\.type === "[A-Z_]+"' "$BG" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/bg_handled.txt"

# 2. Get all types sent from popup.js (type: "TYPE")
grep -oE 'type: "[A-Z_]+"' "$POP" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/popup_sent.txt"

# 3. Get all types sent from content.js
grep -oE 'type: "[A-Z_]+"' "$CS" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/content_sent.txt"

# 4. Get all types handled by content.js
grep -oE 'msg\.type === "[A-Z_]+"' "$CS" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/content_handled.txt"

# For each handled type in background.js, trace the flow
while read -r msgtype; do
  [ -z "$msgtype" ] && continue

  # Determine sender(s)
  senders=""
  if grep -qx "$msgtype" "$TMP_DIR/popup_sent.txt" 2>/dev/null; then
    senders="popup.js"
  fi
  if grep -qx "$msgtype" "$TMP_DIR/content_sent.txt" 2>/dev/null; then
    [ -n "$senders" ] && senders="$senders, "
    senders="${senders}content.js"
  fi
  [ -z "$senders" ] && senders="background.js (internal)"

  handler="background.js"

  # Find associated server endpoint: look within 30 lines after msg.type match
  endpoint=$(grep -A 30 "msg.type === \"$msgtype\"" "$BG" 2>/dev/null \
    | grep -oE 'api\("[^"]+"' | head -1 | grep -oE '"[^"]+"' | tr -d '"' || true)
  [ -z "$endpoint" ] && endpoint="—"

  echo "| \`$msgtype\` | $senders | $handler | \`$endpoint\` |"
done < "$TMP_DIR/bg_handled.txt" >> "$OUTPUT"

# Add content.js-only handled types
while read -r msgtype; do
  [ -z "$msgtype" ] && continue
  if ! grep -qx "$msgtype" "$TMP_DIR/bg_handled.txt" 2>/dev/null; then
    echo "| \`$msgtype\` | background.js | content.js | — |"
  fi
done < "$TMP_DIR/content_handled.txt" >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 3: Extension → Server API Calls ────────────────────────────────

echo "## Extension → Server Endpoint Map" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "All server endpoints called from the extension, grouped by caller." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### background.js → api() calls" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Server Endpoint | Context (nearby message type) |" >> "$OUTPUT"
echo "|---|---|" >> "$OUTPUT"

grep -n 'api("' "$BG" 2>/dev/null | while IFS=: read -r lineno rest; do
  endpoint=$(echo "$rest" | grep -oE 'api\("[^"]+"' | head -1 | grep -oE '"[^"]+"' | tr -d '"')
  [ -z "$endpoint" ] && continue
  # Search backwards for nearest msg.type
  msgtype=$(head -n "$lineno" "$BG" | grep -oE 'msg\.type === "[^"]+"' | tail -1 | grep -oE '"[^"]+"' | tr -d '"' || true)
  [ -z "$msgtype" ] && msgtype="(top-level)"
  echo "| \`api/$endpoint\` | $msgtype handler |"
done >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### popup.js → hsPost() calls" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Server Endpoint | Context (nearby function) |" >> "$OUTPUT"
echo "|---|---|" >> "$OUTPUT"

grep -n 'hsPost("' "$POP" 2>/dev/null | while IFS=: read -r lineno rest; do
  endpoint=$(echo "$rest" | grep -oE 'hsPost\("[^"]+"' | head -1 | grep -oE '"[^"]+"' | tr -d '"')
  [ -z "$endpoint" ] && continue
  # Find nearest function name above
  context=$(head -n "$lineno" "$POP" | grep -oE '(async )?function [a-zA-Z0-9_]+' | tail -1 | sed 's/async //' | sed 's/function //' || true)
  [ -z "$context" ] && context="—"
  echo "| \`api/$endpoint\` | $context() |"
done >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ── Phase 4: PHP Require Graph ───────────────────────────────────────────

echo "## PHP Include Graph" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Which files each PHP endpoint includes via \`require_once\`." >> "$OUTPUT"
echo "" >> "$OUTPUT"

find "$SERVER_DIR" -name '*.php' -not -path '*/vendor/*' | sort | while read -r f; do
  includes=$(grep -oE "require_once __DIR__ \. '[^']+'" "$f" 2>/dev/null | grep -oE "'[^']+'" | tr -d "'" || true)
  if [ -n "$includes" ]; then
    rel=$(relpath "$f")
    echo "**$rel**"
    echo "$includes" | while read -r inc; do
      echo "  → \`$inc\`"
    done
    echo ""
  fi
done >> "$OUTPUT"

# ── Phase 5: PHP Function Definitions ────────────────────────────────────

echo "## PHP Function Registry" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Every function defined in the codebase, where it lives, and where it's called from." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Build function -> file map
grep -rnE '^\s*function [a-zA-Z_][a-zA-Z0-9_]*\s*\(' "$SERVER_DIR" --include='*.php' 2>/dev/null | while IFS=: read -r filepath lineno rest; do
  funcname=$(echo "$rest" | grep -oE 'function [a-zA-Z_][a-zA-Z0-9_]*' | sed 's/function //')
  [ -z "$funcname" ] && continue
  rel=$(relpath "$filepath")
  echo "$funcname|$rel|$lineno"
done | sort > "$TMP_DIR/func_defs.txt"

# Group by file
current_file=""
while IFS='|' read -r funcname filepath lineno; do
  [ -z "$funcname" ] && continue

  if [ "$filepath" != "$current_file" ]; then
    [ -n "$current_file" ] && echo "" >> "$OUTPUT"
    echo "### $filepath" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "| Function | Line | Called From |" >> "$OUTPUT"
    echo "|---|---|---|" >> "$OUTPUT"
    current_file="$filepath"
  fi

  # Find callers — files that contain funcname( but aren't just the definition
  callers=$(grep -rlE "${funcname}\s*\(" "$SERVER_DIR" --include='*.php' 2>/dev/null | while read -r cf; do
    crel=$(relpath "$cf")
    if [ "$crel" = "$filepath" ]; then
      count=$(grep -cE "${funcname}\s*\(" "$cf" 2>/dev/null || echo 0)
      if [ "$count" -gt 1 ]; then
        echo "$crel"
      fi
    else
      echo "$crel"
    fi
  done | sort -u | tr '\n' ', ' | sed 's/, $//')

  [ -z "$callers" ] && callers="—"

  echo "| \`$funcname()\` | $lineno | $callers |"
done < "$TMP_DIR/func_defs.txt" >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 6: Shared Helper Usage Matrix ──────────────────────────────────

echo "## Shared Helper Usage Matrix" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Critical utility functions and every file that calls them." >> "$OUTPUT"
echo "" >> "$OUTPUT"

HELPERS=(
  "cfg"
  "json_input"
  "get_client_id_or_fail"
  "rate_limit_or_fail"
  "rate_limit_check"
  "api_ok"
  "api_ok_flat"
  "api_error"
  "api_log"
  "safe_file_path"
  "atomic_write_json"
  "ensure_dir_secure"
  "temp_code_store"
  "temp_code_retrieve_and_delete"
  "redact_pii_recursive"
  "load_pb_token"
  "save_pb_token"
  "clear_pb_token"
  "load_hs_tokens"
  "save_hs_tokens"
  "clear_hs_tokens"
  "load_close_tokens"
  "save_close_tokens"
  "clear_close_tokens"
  "load_apollo_tokens"
  "save_apollo_tokens"
  "clear_apollo_tokens"
  "pb_call_dialsession"
  "save_session_state"
  "load_session_state"
  "log_msg"
  "http_post_form"
  "pb_api_call"
  "save_user_settings"
  "load_user_settings"
  "save_user_profile"
  "resolve_member_user_id_for_client"
)

echo "| Helper | Used By (files) |" >> "$OUTPUT"
echo "|---|---|" >> "$OUTPUT"

for helper in "${HELPERS[@]}"; do
  files=$(grep -rlE "${helper}\s*\(" "$SERVER_DIR" --include='*.php' 2>/dev/null | while read -r f; do
    relpath "$f"
  done | sort -u | tr '\n' ', ' | sed 's/, $//')
  [ -z "$files" ] && files="—"
  echo "| \`$helper()\` | $files |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 7: API Endpoint Details ────────────────────────────────────────

echo "## API Endpoint Details" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Each endpoint, which shared helpers it uses, and its response style." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "| Endpoint | Rate Limited | Auth Check | Response Style | CRM Helpers |" >> "$OUTPUT"
echo "|---|---|---|---|---|" >> "$OUTPUT"

find "$SERVER_DIR/api" -name '*.php' -not -name 'bootstrap.php' | sort | while read -r f; do
  rel=$(relpath "$f")
  content=$(cat "$f")

  if echo "$content" | grep -qE 'rate_limit_or_fail'; then
    ratelim="Yes"
  else
    ratelim="**NO**"
  fi

  if echo "$content" | grep -qE 'get_client_id_or_fail'; then
    auth="Yes"
  else
    auth="**NO**"
  fi

  if echo "$content" | grep -qE 'api_ok_flat'; then
    resp="api_ok_flat"
  elif echo "$content" | grep -qE 'api_ok[^_]'; then
    resp="api_ok"
  elif echo "$content" | grep -qE 'PB_BOOTSTRAP_NO_JSON'; then
    resp="HTML/redirect"
  else
    resp="custom"
  fi

  helpers=$(echo "$content" | grep -oE 'require_once.*[a-z]+_helpers\.php' | grep -oE '[a-z_]+_helpers\.php' | tr '\n' ', ' | sed 's/, $//' || true)
  [ -z "$helpers" ] && helpers="—"

  echo "| \`$rel\` | $ratelim | $auth | $resp | $helpers |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 8: Webhook Flow ────────────────────────────────────────────────

echo "## Webhook Endpoints" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Webhooks called by PhoneBurner during dial sessions." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "| Webhook | Trigger | Updates | Call Loggers |" >> "$OUTPUT"
echo "|---|---|---|---|" >> "$OUTPUT"

find "$SERVER_DIR/webhooks" -name '*.php' 2>/dev/null | sort | while read -r f; do
  rel=$(relpath "$f")
  content=$(cat "$f")
  bname=$(basename "$f" .php)

  loggers=$(echo "$content" | grep -oE '[a-z_]+_call_logger\.php' | tr '\n' ', ' | sed 's/, $//' || true)
  [ -z "$loggers" ] && loggers="—"

  updates=""
  if echo "$content" | grep -qE 'save_session_state'; then
    updates="session state"
  fi
  if echo "$content" | grep -qE 'daily_stats'; then
    [ -n "$updates" ] && updates="$updates, "
    updates="${updates}daily stats"
  fi
  [ -z "$updates" ] && updates="session state"

  echo "| \`$rel\` | PB \`api_${bname}\` | $updates | $loggers |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 9: CRM Provider Summary ───────────────────────────────────────

echo "## CRM Provider Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Provider | Level | Server Directory | Files | Extension Integration |" >> "$OUTPUT"
echo "|---|---|---|---|---|" >> "$OUTPUT"

for provider_dir in "$SERVER_DIR/api/crm"/*/; do
  [ -d "$provider_dir" ] || continue
  provider=$(basename "$provider_dir")
  rel_dir=$(relpath "$provider_dir")

  if [ "$provider" = "generic" ]; then
    level="L1/L2"
    integration="content.js scan → background.js"
  else
    level="L3"
    integration="popup.js + background.js"
  fi

  files=$(find "$provider_dir" -name '*.php' -exec basename {} \; | sort | tr '\n' ', ' | sed 's/, $//')

  echo "| $provider | $level | \`$rel_dir\` | $files | $integration |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 10: Danger Zone — High-Impact Shared Code ─────────────────────

echo "## Danger Zone — High-Impact Shared Code" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "These files/functions are used by many endpoints. Changes here have the widest blast radius." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "| File/Function | Dependents | Risk |" >> "$OUTPUT"
echo "|---|---|---|" >> "$OUTPUT"

for key_file in "utils.php" "bootstrap.php"; do
  dep_count=$(grep -rlE "require_once.*$key_file" "$SERVER_DIR" --include='*.php' 2>/dev/null | wc -l)
  echo "| \`$key_file\` | $dep_count files include it | **CRITICAL** — changes affect all endpoints |"
done >> "$OUTPUT"

for func in "api_ok" "api_error" "get_client_id_or_fail" "rate_limit_or_fail" "pb_call_dialsession"; do
  dep_count=$(grep -rlE "${func}\s*\(" "$SERVER_DIR" --include='*.php' 2>/dev/null | wc -l)
  echo "| \`$func()\` | $dep_count files call it | **HIGH** — signature change breaks callers |"
done >> "$OUTPUT"

for msgtype in "GET_STATE" "GET_CONTEXT" "SCANNED_CONTACTS"; do
  dep_count=0
  for jsfile in "$BG" "$POP" "$CS"; do
    if grep -qE "\"$msgtype\"" "$jsfile" 2>/dev/null; then
      dep_count=$((dep_count + 1))
    fi
  done
  echo "| Message: \`$msgtype\` | referenced in $dep_count JS files | **HIGH** — renaming breaks extension |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Footer ────────────────────────────────────────────────────────────────

cat >> "$OUTPUT" << 'FOOTER'
---

*This map is auto-generated. Run `./scripts/generate-project-map.sh` to regenerate.*
*Integrated into the PR workflow via Claude Code hook.*
FOOTER

echo "PROJECT_MAP.md generated successfully ($TIMESTAMP)"
