#!/usr/bin/env bash
#
# Generate PROJECT_MAP.md — a dependency map of the entire codebase.
#
# Usage:
#   ./scripts/generate-project-map.sh
#
# This script scans all PHP and JS source files and produces a machine-readable
# dependency map at the project root. It traces function definitions and callers,
# Chrome extension message flows, server endpoint usage, and shared helper usage.
# It resolves callers to the function level (not just file) and traces call chains.
#
# Run before every PR to keep the map current. Integrated via Claude Code hook.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$PROJECT_ROOT/PROJECT_MAP.md"

SERVER_DIR="$PROJECT_ROOT/server/public"
EXT_DIR="$PROJECT_ROOT/chrome-extension"

# Temp files
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# ── Helpers ───────────────────────────────────────────────────────────────

relpath() {
  local abs="$1"
  abs="${abs//\\//}"
  local root="${PROJECT_ROOT//\\//}"
  echo "${abs#"$root"/}"
}

# Build function range index: file|funcname|start|end for every PHP function
# Also outputs top-level ranges for code outside functions
build_function_ranges() {
  find "$SERVER_DIR" -name '*.php' -not -path '*/vendor/*' | sort | while read -r f; do
    awk '
    BEGIN { depth=0; in_func=0; funcname="(top-level)"; start=1 }
    /^\s*function [a-zA-Z_]/ {
      if (in_func == 0 && funcname == "(top-level)" && NR > start) {
        print FILENAME "|" funcname "|" start "|" NR-1
      }
      funcname=$0
      sub(/.*function /, "", funcname)
      sub(/\(.*/, "", funcname)
      start=NR
      in_func=1
      depth=0
    }
    in_func {
      n = gsub(/{/, "{")
      depth += n
      n = gsub(/}/, "}")
      depth -= n
      if (depth <= 0 && NR > start) {
        print FILENAME "|" funcname "|" start "|" NR
        in_func=0
        funcname="(top-level)"
        start=NR+1
      }
    }
    END {
      if (funcname != "") {
        print FILENAME "|" funcname "|" start "|" NR
      }
    }
    ' "$f"
  done
}

# Resolve which function contains a call to $target_func in $file at $line
# Uses the pre-built ranges file
resolve_caller_func() {
  local file="$1" line="$2"
  # Normalize file path
  file="${file//\\//}"
  awk -F'|' -v f="$file" -v l="$line" '
  {
    gsub(/\\/, "/", $1)
    if ($1 == f && l >= $3 && l <= $4 && $2 != "(top-level)") {
      print $2
      exit
    }
  }
  ' "$TMP_DIR/func_ranges.txt"
}

# Boilerplate functions to filter from cross-boundary chains.
# These appear in virtually every endpoint and add noise, not signal.
BOILERPLATE="api_error|api_ok|api_ok_flat|api_log|json_input|get_client_id_or_fail|rate_limit_or_fail|rate_limit_check|cfg|log_msg|json_response|redact_pii_recursive|ensure_dir"

# Check if a function name is boilerplate
is_boilerplate() {
  echo "$1" | grep -qE "^(${BOILERPLATE})$"
}

# ── Pre-compute function ranges ──────────────────────────────────────────

echo "Building function range index..." >&2
build_function_ranges > "$TMP_DIR/func_ranges.txt"
echo "  $(wc -l < "$TMP_DIR/func_ranges.txt") ranges indexed" >&2

# ── Header ────────────────────────────────────────────────────────────────

TIMESTAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
COMMIT=$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "$OUTPUT" << 'HEADER'
# PROJECT_MAP.md — Dependency Map

<!-- AUTO-GENERATED by scripts/generate-project-map.sh — do not edit manually -->
HEADER

echo "<!-- Last generated: $TIMESTAMP | Commit: $COMMIT -->" >> "$OUTPUT"

cat >> "$OUTPUT" << 'INTRO'

This file maps every function, message type, endpoint, and dependency in the
project so that any change can be traced to everything it affects. Consult this
before modifying shared code.

---

INTRO

# ── Phase 1: File Inventory ──────────────────────────────────────────────

echo "## File Inventory" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Server PHP Files" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
find "$SERVER_DIR" -name '*.php' -not -path '*/vendor/*' | sort | while read -r f; do
  lines=$(wc -l < "$f")
  echo "$(relpath "$f")  ($lines lines)"
done >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Extension JS Files" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
find "$EXT_DIR" -name '*.js' | sort | while read -r f; do
  lines=$(wc -l < "$f")
  echo "$(relpath "$f")  ($lines lines)"
done >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ── Phase 2: Chrome Message Flow ─────────────────────────────────────────

echo "## Chrome Message Flow" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Maps every message type: where it's sent from, where it's handled, and what server endpoint it hits." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Message Type | Sent From | Handled In | Server Endpoint |" >> "$OUTPUT"
echo "|---|---|---|---|" >> "$OUTPUT"

BG="$EXT_DIR/background.js"
POP="$EXT_DIR/popup.js"
CS="$EXT_DIR/content.js"

grep -oE 'msg\.type === "[A-Z_]+"' "$BG" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/bg_handled.txt"
grep -oE 'type: "[A-Z_]+"' "$POP" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/popup_sent.txt"
grep -oE 'type: "[A-Z_]+"' "$CS" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/content_sent.txt"
grep -oE 'msg\.type === "[A-Z_]+"' "$CS" 2>/dev/null | grep -oE '"[^"]+"' | tr -d '"' | sort -u > "$TMP_DIR/content_handled.txt"

# Also extract ALL api() endpoints per message type for cross-boundary chains later
> "$TMP_DIR/msg_to_endpoints.txt"

while read -r msgtype; do
  [ -z "$msgtype" ] && continue

  senders=""
  if grep -qx "$msgtype" "$TMP_DIR/popup_sent.txt" 2>/dev/null; then
    senders="popup.js"
  fi
  if grep -qx "$msgtype" "$TMP_DIR/content_sent.txt" 2>/dev/null; then
    [ -n "$senders" ] && senders="$senders, "
    senders="${senders}content.js"
  fi
  [ -z "$senders" ] && senders="background.js (internal)"

  handler="background.js"

  # Collect ALL api() endpoints within this handler block
  endpoints=$(grep -A 50 "msg.type === \"$msgtype\"" "$BG" 2>/dev/null \
    | grep -oE 'api\("[^"]+"' | grep -oE '"[^"]+"' | tr -d '"' | tr '\n' ',' | sed 's/,$//' || true)
  display_endpoint=$(echo "$endpoints" | cut -d',' -f1)
  [ -z "$display_endpoint" ] && display_endpoint="—"

  # Save for cross-boundary chains
  if [ -n "$endpoints" ]; then
    echo "$msgtype|$senders|$endpoints" >> "$TMP_DIR/msg_to_endpoints.txt"
  fi

  echo "| \`$msgtype\` | $senders | $handler | \`$display_endpoint\` |"
done < "$TMP_DIR/bg_handled.txt" >> "$OUTPUT"

while read -r msgtype; do
  [ -z "$msgtype" ] && continue
  if ! grep -qx "$msgtype" "$TMP_DIR/bg_handled.txt" 2>/dev/null; then
    echo "| \`$msgtype\` | background.js | content.js | — |"
  fi
done < "$TMP_DIR/content_handled.txt" >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 3: Extension → Server API Calls ────────────────────────────────

echo "## Extension → Server Endpoint Map" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "All server endpoints called from the extension, grouped by caller." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### background.js → api() calls" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Server Endpoint | Context (nearby message type) |" >> "$OUTPUT"
echo "|---|---|" >> "$OUTPUT"

grep -n 'api("' "$BG" 2>/dev/null | while IFS=: read -r lineno rest; do
  endpoint=$(echo "$rest" | grep -oE 'api\("[^"]+"' | head -1 | grep -oE '"[^"]+"' | tr -d '"')
  [ -z "$endpoint" ] && continue
  msgtype=$(head -n "$lineno" "$BG" | grep -oE 'msg\.type === "[^"]+"' | tail -1 | grep -oE '"[^"]+"' | tr -d '"' || true)
  [ -z "$msgtype" ] && msgtype="(top-level)"
  echo "| \`api/$endpoint\` | $msgtype handler |"
done >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### popup.js → hsPost() calls" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Server Endpoint | Context (nearby function) |" >> "$OUTPUT"
echo "|---|---|" >> "$OUTPUT"

# Also save popup direct calls for cross-boundary chains
> "$TMP_DIR/popup_direct_calls.txt"

grep -n 'hsPost("' "$POP" 2>/dev/null | while IFS=: read -r lineno rest; do
  endpoint=$(echo "$rest" | grep -oE 'hsPost\("[^"]+"' | head -1 | grep -oE '"[^"]+"' | tr -d '"')
  [ -z "$endpoint" ] && continue
  context=$(head -n "$lineno" "$POP" | grep -oE '(async )?function [a-zA-Z0-9_]+' | tail -1 | sed 's/async //' | sed 's/function //' || true)
  [ -z "$context" ] && context="—"
  echo "| \`api/$endpoint\` | $context() |"
  echo "$context|$endpoint" >> "$TMP_DIR/popup_direct_calls.txt"
done >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ── Phase 4: PHP Require Graph ───────────────────────────────────────────

echo "## PHP Include Graph" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Which files each PHP endpoint includes via \`require_once\`." >> "$OUTPUT"
echo "" >> "$OUTPUT"

find "$SERVER_DIR" -name '*.php' -not -path '*/vendor/*' | sort | while read -r f; do
  includes=$(grep -oE "require_once __DIR__ \. '[^']+'" "$f" 2>/dev/null | grep -oE "'[^']+'" | tr -d "'" || true)
  if [ -n "$includes" ]; then
    rel=$(relpath "$f")
    echo "**$rel**"
    echo "$includes" | while read -r inc; do
      echo "  → \`$inc\`"
    done
    echo ""
  fi
done >> "$OUTPUT"

# ── Phase 5: PHP Function Registry (Enhanced: function-level callers) ────

echo "## PHP Function Registry" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Every function, where it lives, and which **functions** call it (not just files)." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Build function -> file map
grep -rnE '^\s*function [a-zA-Z_][a-zA-Z0-9_]*\s*\(' "$SERVER_DIR" --include='*.php' 2>/dev/null | while IFS=: read -r filepath lineno rest; do
  funcname=$(echo "$rest" | grep -oE 'function [a-zA-Z_][a-zA-Z0-9_]*' | sed 's/function //')
  [ -z "$funcname" ] && continue
  rel=$(relpath "$filepath")
  echo "$funcname|$rel|$lineno"
done | sort -t'|' -k2,2 -k1,1 > "$TMP_DIR/func_defs.txt"

# Pre-build a caller map: for each function, find which functions call it
# Output: callee|caller_func|caller_file
echo "Building function-level call graph..." >&2

> "$TMP_DIR/call_graph.txt"

while IFS='|' read -r funcname filepath defline; do
  [ -z "$funcname" ] && continue

  # Find all call sites across all PHP files
  grep -rnE "${funcname}\s*\(" "$SERVER_DIR" --include='*.php' 2>/dev/null | while IFS=: read -r cf clineno crest; do
    # Skip the definition line itself
    crel=$(relpath "$cf")
    if [ "$crel" = "$filepath" ] && [ "$clineno" = "$defline" ]; then
      continue
    fi

    # Resolve which function this call site is inside of
    cf_normalized="${cf//\\//}"
    caller_func=$(awk -F'|' -v f="$cf_normalized" -v l="$clineno" '
    {
      gsub(/\\/, "/", $1)
      if ($1 == f && l+0 >= $3+0 && l+0 <= $4+0 && $2 != "(top-level)") {
        print $2
        found=1
        exit
      }
    }
    END { if (!found) print "(top-level)" }
    ' "$TMP_DIR/func_ranges.txt")

    echo "$funcname|$caller_func|$crel"
  done
done < "$TMP_DIR/func_defs.txt" >> "$TMP_DIR/call_graph.txt"

echo "  $(wc -l < "$TMP_DIR/call_graph.txt") call edges found" >&2

# Now output the registry grouped by file, with function-level callers
current_file=""
while IFS='|' read -r funcname filepath lineno; do
  [ -z "$funcname" ] && continue

  if [ "$filepath" != "$current_file" ]; then
    [ -n "$current_file" ] && echo "" >> "$OUTPUT"
    echo "### $filepath" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "| Function | Line | Called By |" >> "$OUTPUT"
    echo "|---|---|---|" >> "$OUTPUT"
    current_file="$filepath"
  fi

  # Get function-level callers from the call graph
  callers=""
  while IFS='|' read -r _ caller_func caller_file; do
    entry=""
    if [ "$caller_func" = "(top-level)" ]; then
      entry="$caller_file"
    else
      entry="\`${caller_func}()\` in $caller_file"
    fi
    if [ -n "$callers" ]; then
      callers="$callers, $entry"
    else
      callers="$entry"
    fi
  done < <(grep "^${funcname}|" "$TMP_DIR/call_graph.txt" 2>/dev/null | sort -t'|' -k2,3 -u || true)

  [ -z "$callers" ] && callers="—"

  echo "| \`$funcname()\` | $lineno | $callers |"
done < "$TMP_DIR/func_defs.txt" >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 6: API Endpoint Details ────────────────────────────────────────
# (Shared Helper Usage Matrix removed — redundant with function-level callers in Phase 5)

echo "## API Endpoint Details" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Each endpoint, which shared helpers it uses, and its response style." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "| Endpoint | Rate Limited | Auth Check | Response Style | CRM Helpers |" >> "$OUTPUT"
echo "|---|---|---|---|---|" >> "$OUTPUT"

find "$SERVER_DIR/api" -name '*.php' -not -name 'bootstrap.php' | sort | while read -r f; do
  rel=$(relpath "$f")
  content=$(cat "$f")

  if echo "$content" | grep -qE 'rate_limit_or_fail'; then
    ratelim="Yes"
  else
    ratelim="**NO**"
  fi

  if echo "$content" | grep -qE 'get_client_id_or_fail'; then
    auth="Yes"
  else
    auth="**NO**"
  fi

  if echo "$content" | grep -qE 'api_ok_flat'; then
    resp="api_ok_flat"
  elif echo "$content" | grep -qE 'api_ok[^_]'; then
    resp="api_ok"
  elif echo "$content" | grep -qE 'PB_BOOTSTRAP_NO_JSON'; then
    resp="HTML/redirect"
  else
    resp="custom"
  fi

  helpers=$(echo "$content" | grep -oE 'require_once.*[a-z]+_helpers\.php' | grep -oE '[a-z_]+_helpers\.php' | tr '\n' ', ' | sed 's/, $//' || true)
  [ -z "$helpers" ] && helpers="—"

  echo "| \`$rel\` | $ratelim | $auth | $resp | $helpers |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 8: Webhook Flow ────────────────────────────────────────────────

echo "## Webhook Endpoints" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Webhooks called by PhoneBurner during dial sessions." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "| Webhook | Trigger | Updates | Call Loggers |" >> "$OUTPUT"
echo "|---|---|---|---|" >> "$OUTPUT"

find "$SERVER_DIR/webhooks" -name '*.php' 2>/dev/null | sort | while read -r f; do
  rel=$(relpath "$f")
  content=$(cat "$f")
  bname=$(basename "$f" .php)

  loggers=$(echo "$content" | grep -oE '[a-z_]+_call_logger\.php' | tr '\n' ', ' | sed 's/, $//' || true)
  [ -z "$loggers" ] && loggers="—"

  updates=""
  if echo "$content" | grep -qE 'save_session_state'; then
    updates="session state"
  fi
  if echo "$content" | grep -qE 'daily_stats'; then
    [ -n "$updates" ] && updates="$updates, "
    updates="${updates}daily stats"
  fi
  [ -z "$updates" ] && updates="session state"

  echo "| \`$rel\` | PB \`api_${bname}\` | $updates | $loggers |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 9: CRM Provider Summary ───────────────────────────────────────

echo "## CRM Provider Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Provider | Level | Server Directory | Files | Extension Integration |" >> "$OUTPUT"
echo "|---|---|---|---|---|" >> "$OUTPUT"

for provider_dir in "$SERVER_DIR/api/crm"/*/; do
  [ -d "$provider_dir" ] || continue
  provider=$(basename "$provider_dir")
  rel_dir=$(relpath "$provider_dir")

  if [ "$provider" = "generic" ]; then
    level="L1/L2"
    integration="content.js scan → background.js"
  else
    level="L3"
    integration="popup.js + background.js"
  fi

  files=$(find "$provider_dir" -name '*.php' -exec basename {} \; | sort | tr '\n' ', ' | sed 's/, $//')

  echo "| $provider | $level | \`$rel_dir\` | $files | $integration |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 10: Danger Zone — High-Impact Shared Code ─────────────────────

echo "## Danger Zone — High-Impact Shared Code" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "These files/functions are used by many endpoints. Changes here have the widest blast radius." >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "| File/Function | Dependents | Risk |" >> "$OUTPUT"
echo "|---|---|---|" >> "$OUTPUT"

for key_file in "utils.php" "bootstrap.php"; do
  dep_count=$(grep -rlE "require_once.*$key_file" "$SERVER_DIR" --include='*.php' 2>/dev/null | wc -l)
  echo "| \`$key_file\` | $dep_count files include it | **CRITICAL** — changes affect all endpoints |"
done >> "$OUTPUT"

for func in "api_ok" "api_error" "get_client_id_or_fail" "rate_limit_or_fail" "pb_call_dialsession"; do
  dep_count=$(grep -rlE "${func}\s*\(" "$SERVER_DIR" --include='*.php' 2>/dev/null | wc -l)
  echo "| \`$func()\` | $dep_count files call it | **HIGH** — signature change breaks callers |"
done >> "$OUTPUT"

for msgtype in "GET_STATE" "GET_CONTEXT" "SCANNED_CONTACTS"; do
  dep_count=0
  for jsfile in "$BG" "$POP" "$CS"; do
    if grep -qE "\"$msgtype\"" "$jsfile" 2>/dev/null; then
      dep_count=$((dep_count + 1))
    fi
  done
  echo "| Message: \`$msgtype\` | referenced in $dep_count JS files | **HIGH** — renaming breaks extension |"
done >> "$OUTPUT"

echo "" >> "$OUTPUT"

# ── Phase 11: Call Chains for Critical Functions ─────────────────────────
# Disable pipefail for this section — nested grep pipelines produce benign
# SIGPIPE when one side closes early
set +o pipefail

echo "## Call Chains — Critical Functions" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Multi-level call chains for high-impact functions. Read bottom-up: the" >> "$OUTPUT"
echo "lowest level is the utility, each line above is a caller of the line below." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# For each critical utility function, trace up 3 levels using pre-built graph
# Trace chains for functions with moderate fan-out (not api_error/api_ok which
# are called everywhere — those are already in the Danger Zone section)
CRITICAL_FUNCS=(
  "atomic_write_json"
  "temp_code_store"
  "pb_call_dialsession"
  "save_session_state"
  "http_post_form"
  "safe_file_path"
  "temp_code_retrieve_and_delete"
)

for root_func in "${CRITICAL_FUNCS[@]}"; do
  echo "### \`$root_func()\`" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"

  # Build chain file for this function — avoids nested subshells with head/pipe
  > "$TMP_DIR/chain_out.txt"

  # Level 1: direct callers of root_func
  grep "^${root_func}|" "$TMP_DIR/call_graph.txt" 2>/dev/null | sort -t'|' -k2,3 -u | while IFS='|' read -r _ l1_func l1_file; do
    [ "$l1_func" = "(top-level)" ] && l1_func="(script)"
    l1_short=$(basename "$l1_file")
    echo "L1|${l1_func}|${l1_short}|${l1_file}" >> "$TMP_DIR/chain_out.txt"

    # Level 2: callers of l1_func (skip if script-level)
    if [ "$l1_func" != "(script)" ]; then
      grep "^${l1_func}|" "$TMP_DIR/call_graph.txt" 2>/dev/null | sort -t'|' -k2,3 -u | while IFS='|' read -r _ l2_func l2_file; do
        [ "$l2_func" = "(top-level)" ] && l2_func="(script)"
        l2_short=$(basename "$l2_file")
        echo "L2|${l1_func}|${l2_func}|${l2_short}" >> "$TMP_DIR/chain_out.txt"

        # Level 3: callers of l2_func
        if [ "$l2_func" != "(script)" ]; then
          grep "^${l2_func}|" "$TMP_DIR/call_graph.txt" 2>/dev/null | sort -t'|' -k2,3 -u | while IFS='|' read -r _ l3_func l3_file; do
            [ "$l3_func" = "(top-level)" ] && l3_func="(script)"
            l3_short=$(basename "$l3_file")
            echo "L3|${l2_func}|${l3_func}|${l3_short}" >> "$TMP_DIR/chain_out.txt"
          done
        fi
      done
    fi
  done

  # Format the chain output
  {
    # Show L3 → L2 → L1 → root
    grep '^L3|' "$TMP_DIR/chain_out.txt" 2>/dev/null | sort -u | while IFS='|' read -r _ parent func file; do
      echo "  ${func}() ← ${file}"
    done
    grep '^L2|' "$TMP_DIR/chain_out.txt" 2>/dev/null | sort -u | while IFS='|' read -r _ parent func file; do
      echo "    → ${func}() ← ${file}"
    done
    grep '^L1|' "$TMP_DIR/chain_out.txt" 2>/dev/null | sort -u | while IFS='|' read -r _ func file _; do
      echo "      → ${func}() ← ${file}"
    done
    echo "        → ${root_func}()"
  } >> "$OUTPUT"

  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

# ── Phase 12: Cross-Boundary Chains (UI → JS → PHP → Utility) ───────────

echo "## Cross-Boundary Chains — Full Stack Traces" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "End-to-end flow from UI action through extension JS to server PHP to utility functions." >> "$OUTPUT"
echo "Each chain shows: popup/content.js → background.js handler → server endpoint → PHP functions called." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# For each message type that hits a server endpoint, trace the full chain
while IFS='|' read -r msgtype senders endpoints; do
  [ -z "$msgtype" ] && continue

  echo "### \`$msgtype\`" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  echo "$senders" >> "$OUTPUT"
  echo "  → background.js ($msgtype handler)" >> "$OUTPUT"

  # For each endpoint this handler calls
  IFS=',' read -ra ep_array <<< "$endpoints"
  for ep in "${ep_array[@]}"; do
    ep=$(echo "$ep" | tr -d ' ')
    [ -z "$ep" ] && continue
    echo "    → api/$ep" >> "$OUTPUT"

    # Find which functions this endpoint file calls (top-level calls)
    ep_file="$SERVER_DIR/api/$ep"
    if [ -f "$ep_file" ]; then
      # Get domain-specific function calls (filter out boilerplate)
      ep_rel=$(relpath "$ep_file")
      {
        grep "|(top-level)|${ep_rel}$" "$TMP_DIR/call_graph.txt" 2>/dev/null | while IFS='|' read -r called_func _ _; do
          is_boilerplate "$called_func" && continue
          echo "      → $called_func()"

          # One more level: what does that function call?
          grep "^.*|${called_func}|" "$TMP_DIR/call_graph.txt" 2>/dev/null | sort -t'|' -k1,1 -u | while IFS='|' read -r subcall _ _; do
            is_boilerplate "$subcall" && continue
            echo "        → $subcall()"
          done
        done
      } | sort -u >> "$OUTPUT"
    fi
  done

  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done < "$TMP_DIR/msg_to_endpoints.txt" >> "$OUTPUT"

# Also trace popup.js direct calls (hsPost)
if [ -s "$TMP_DIR/popup_direct_calls.txt" ]; then
  echo "### popup.js → Direct Server Calls" >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  while IFS='|' read -r popup_func endpoint; do
    [ -z "$endpoint" ] && continue
    echo "**\`$popup_func()\`** → \`api/$endpoint\`" >> "$OUTPUT"

    ep_file="$SERVER_DIR/api/$endpoint"
    if [ -f "$ep_file" ]; then
      ep_rel=$(relpath "$ep_file")
      calls=$(grep "|(top-level)|${ep_rel}$" "$TMP_DIR/call_graph.txt" 2>/dev/null | while IFS='|' read -r called_func _ _; do
        is_boilerplate "$called_func" && continue
        echo "$called_func()"
      done | sort -u | tr '\n' ', ' | sed 's/,$//' | sed 's/, $//')
      if [ -n "$calls" ]; then
        echo "  → $calls" >> "$OUTPUT"
      fi
    fi
    echo "" >> "$OUTPUT"
  done < "$TMP_DIR/popup_direct_calls.txt" >> "$OUTPUT"
fi

# Re-enable pipefail for the rest
set -o pipefail

# ── Footer ────────────────────────────────────────────────────────────────

cat >> "$OUTPUT" << 'FOOTER'
---

*This map is auto-generated. Run `./scripts/generate-project-map.sh` to regenerate.*
*Integrated into the PR workflow via Claude Code hook.*
FOOTER

LINES=$(wc -l < "$OUTPUT")
echo "PROJECT_MAP.md generated successfully — $LINES lines ($TIMESTAMP)" >&2
